### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by stuaxo**
Remove random 'o' from Dockerfile

### CODE REVIEW

**Comment by stuaxo** [comment]
Hi,
   @kiamesdavies 

Any chance of merging this ?

Cheers
Stuart

**Comment by stuaxo** [comment]
Cheers :)

**Comment by kiamesdavies** [comment]
Great job, hope u find the build useful

**Comment by stuaxo** [comment]
With my free time it will probably be a while, but don't be surprised if I'm back in a year or more :)

**Pull request merged**
